### ISSUE TITLE
Summary Test for next milestone

### ISSUE THREAD

**Issue by aylapear** [UBC-MDS/KMediansPy#27]
- [x] create a test to confirm X Coordinates of Final Medians
- [x] create a test to confirm Y Coordinates of Final Medians
- [x]  write test to test fail for wrong inputs (strings, integers, etc)
