### ISSUE TITLE
Milestone 3 - Work Plan

### ISSUE THREAD

**Issue by aylapear** [UBC-MDS/KMediansPy#33]
- [x] rename the folder `test_files` to `tests`
- [x] add the licence 
- [x] add summary tests from other issue "Summary Test for next milestone"
- [x] change the output of the summary function in the readme to image
- [x] fix .any/.all object in test_distance_calc() function
- [x] determine what issue is in KMedians function `NaN to integer error`
