### ISSUE TITLE
Milestone 2 - Work Plan

### ISSUE THREAD

**Issue by aylapear** [UBC-MDS/KMediansPy#9]
- [x] Writing distance function.
- [x] Testing distance function.
- [x] Writing kmedians function.
- [x]  Testing kmedians function.
- [x] Writing summary function.
- [x] Testing summary function.

Following GitHub Flow workflow:
**remember to use branches**
 Code review and feedback for each function:
- [x] Distance
- [x] KMedians
- [x]  Summary

Python Package
- [x]  Make the package importable 
- [x]  Update README with instructions on how to import package

**Comment by aylapear** [comment]
I need to make some minor changes to the test cases written for the summary function. Since it randomly initializes the medians some of the test are failing. 

- [x] set the seed in test_toy_data_summary():
- [x] update the distance calculations in test_toy_data_summary():
- [x] change name of summary function file, cant have '-' in file name

**Comment by aylapear** [comment]
- [x] upload copy of pytest report
